baseURL = 'http://discriminator.tech/'
languageCode = 'en-us'
title = 'Discriminator Tech'
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

theme = "learn"
